/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppStockRouteImport } from './routes/_authenticated/app.stock'
import { Route as AuthenticatedAppStaffRouteImport } from './routes/_authenticated/app.staff'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app.services'
import { Route as AuthenticatedAppClientsRouteImport } from './routes/_authenticated/app.clients'
import { Route as AuthenticatedAppAppointmentsRouteImport } from './routes/_authenticated/app.appointments'
import { Route as AuthenticatedAppClientsIdRouteImport } from './routes/_authenticated/app.clients.$id'
import { Route as AuthenticatedAppStaffIdScheduleRouteImport } from './routes/_authenticated/app.staff.$id.schedule'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppStockRoute = AuthenticatedAppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppStaffRoute = AuthenticatedAppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientsRoute = AuthenticatedAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAppointmentsRoute =
  AuthenticatedAppAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientsIdRoute =
  AuthenticatedAppClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppClientsRoute,
  } as any)
const AuthenticatedAppStaffIdScheduleRoute =
  AuthenticatedAppStaffIdScheduleRouteImport.update({
    id: '/$id/schedule',
    path: '/$id/schedule',
    getParentRoute: () => AuthenticatedAppStaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/appointments': typeof AuthenticatedAppAppointmentsRoute
  '/app/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/staff': typeof AuthenticatedAppStaffRouteWithChildren
  '/app/stock': typeof AuthenticatedAppStockRoute
  '/app/clients/$id': typeof AuthenticatedAppClientsIdRoute
  '/app/staff/$id/schedule': typeof AuthenticatedAppStaffIdScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/appointments': typeof AuthenticatedAppAppointmentsRoute
  '/app/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/staff': typeof AuthenticatedAppStaffRouteWithChildren
  '/app/stock': typeof AuthenticatedAppStockRoute
  '/app/clients/$id': typeof AuthenticatedAppClientsIdRoute
  '/app/staff/$id/schedule': typeof AuthenticatedAppStaffIdScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/appointments': typeof AuthenticatedAppAppointmentsRoute
  '/_authenticated/app/clients': typeof AuthenticatedAppClientsRouteWithChildren
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/staff': typeof AuthenticatedAppStaffRouteWithChildren
  '/_authenticated/app/stock': typeof AuthenticatedAppStockRoute
  '/_authenticated/app/clients/$id': typeof AuthenticatedAppClientsIdRoute
  '/_authenticated/app/staff/$id/schedule': typeof AuthenticatedAppStaffIdScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/appointments'
    | '/app/clients'
    | '/app/services'
    | '/app/staff'
    | '/app/stock'
    | '/app/clients/$id'
    | '/app/staff/$id/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/appointments'
    | '/app/clients'
    | '/app/services'
    | '/app/staff'
    | '/app/stock'
    | '/app/clients/$id'
    | '/app/staff/$id/schedule'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/appointments'
    | '/_authenticated/app/clients'
    | '/_authenticated/app/services'
    | '/_authenticated/app/staff'
    | '/_authenticated/app/stock'
    | '/_authenticated/app/clients/$id'
    | '/_authenticated/app/staff/$id/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/stock': {
      id: '/_authenticated/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AuthenticatedAppStockRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/staff': {
      id: '/_authenticated/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AuthenticatedAppStaffRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clients': {
      id: '/_authenticated/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AuthenticatedAppClientsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/appointments': {
      id: '/_authenticated/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AuthenticatedAppAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clients/$id': {
      id: '/_authenticated/app/clients/$id'
      path: '/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AuthenticatedAppClientsIdRouteImport
      parentRoute: typeof AuthenticatedAppClientsRoute
    }
    '/_authenticated/app/staff/$id/schedule': {
      id: '/_authenticated/app/staff/$id/schedule'
      path: '/$id/schedule'
      fullPath: '/app/staff/$id/schedule'
      preLoaderRoute: typeof AuthenticatedAppStaffIdScheduleRouteImport
      parentRoute: typeof AuthenticatedAppStaffRoute
    }
  }
}

interface AuthenticatedAppClientsRouteChildren {
  AuthenticatedAppClientsIdRoute: typeof AuthenticatedAppClientsIdRoute
}

const AuthenticatedAppClientsRouteChildren: AuthenticatedAppClientsRouteChildren =
  {
    AuthenticatedAppClientsIdRoute: AuthenticatedAppClientsIdRoute,
  }

const AuthenticatedAppClientsRouteWithChildren =
  AuthenticatedAppClientsRoute._addFileChildren(
    AuthenticatedAppClientsRouteChildren,
  )

interface AuthenticatedAppStaffRouteChildren {
  AuthenticatedAppStaffIdScheduleRoute: typeof AuthenticatedAppStaffIdScheduleRoute
}

const AuthenticatedAppStaffRouteChildren: AuthenticatedAppStaffRouteChildren = {
  AuthenticatedAppStaffIdScheduleRoute: AuthenticatedAppStaffIdScheduleRoute,
}

const AuthenticatedAppStaffRouteWithChildren =
  AuthenticatedAppStaffRoute._addFileChildren(
    AuthenticatedAppStaffRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAppointmentsRoute: typeof AuthenticatedAppAppointmentsRoute
  AuthenticatedAppClientsRoute: typeof AuthenticatedAppClientsRouteWithChildren
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppStaffRoute: typeof AuthenticatedAppStaffRouteWithChildren
  AuthenticatedAppStockRoute: typeof AuthenticatedAppStockRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAppointmentsRoute: AuthenticatedAppAppointmentsRoute,
  AuthenticatedAppClientsRoute: AuthenticatedAppClientsRouteWithChildren,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppStaffRoute: AuthenticatedAppStaffRouteWithChildren,
  AuthenticatedAppStockRoute: AuthenticatedAppStockRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
