// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juauzzongtyrxslpmxdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1YXV6em9uZ3R5cnhzbHBteGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQzODM4MjQsImV4cCI6MjA5OTk1OTgyNH0.8TxwJGBI3Rh8amrR1OGI4vLJOHlFphPWRTN_jCG3y0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});